eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: https://localhost:8800/eureka/
  instance:
    securedPort: ${server.port}
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://localhost:${server.port}/actuator/info
    healthCheckUrl: https://localhost:${server.port}/actuator/health
    homePageUrl: https://localhost:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'